stages:
  - code quality
  - testing

variables:
  POSTGRES_DB: market
  POSTGRES_USER: skillbox
  POSTGRES_PASSWORD: secret
  POSTGRES_HOST_AUTH_METHOD: trust
  EMAIL_HOST: "smtp.yandex.ru"
  EMAIL_PORT: 587
  EMAIL_HOST_USER: "meganoshops@yandex.ru"
  EMAIL_HOST_PASSWORD: "lmxgiyelbswrujgz"

services:
  - name: redis:latest
    alias: broker
  - name: postgres:latest
    alias: db

default:
  image: python:3.10.6
  tags:
    - students
  before_script:
    - pip install poetry
    - poetry --version
    - poetry config virtualenvs.in-project true
    - poetry install -vv

flake8:
  stage: code quality
  script:
    - poetry run flake8 market

test:
  stage: testing
  when: always
  variables:
    DATABASE_URL: "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB"
    REDIS_URL: "redis://broker:6379/0"
  script:
    - echo "DATABASE_URL = $DATABASE_URL" >> .env
    - echo "REDIS_URL = $REDIS_URL" >> .env
    - echo "EMAIL_HOST = $EMAIL_HOST" >> .env
    - echo "EMAIL_PORT = $EMAIL_PORT" >> .env
    - echo "EMAIL_HOST_USER = $EMAIL_HOST_USER" >> .env
    - echo "EMAIL_HOST_PASSWORD = $EMAIL_HOST_PASSWORD" >> .env
    - cd market
    - poetry run python manage.py makemigrations
    - poetry run python manage.py test
